### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by anarchistische-ecke** [greg-ynx/NexusDownloadFlow-2022#1]
after i put my pictures into the assets folder, program crashes. are pictures supposed to be of some definite kind, or have some definite named?

**Comment by greg-ynx** [comment]
Hi! Yeah, your pictures should all be in PNG format (.png extension) and named -> template1.png - template2.png - template3.png (according to the readme file)

Did it worked correctly at least once?

I might add logs to NDF 2022 in order to help in resolving issues like yours.

**Comment by anarchistische-ecke** [comment]
renaming helped, thank you!

**Comment by greg-ynx** [comment]
Great! I am closing this issue then.
