### ISSUE TITLE
I have no idea but there is some conflict in the files

### ISSUE THREAD

**Issue by DamnPlotArmor** [greg-ynx/NexusDownloadFlow-2022#42]
Coding is not my forte. So, I'm providing a screenshot of the error. I'm providing a rundown of my actions. I added the custom templates. For that, I ran command .\NexusDownloadFlow.exe add-templates "D:\xxx mods\helpful tools\NexusDownloadFlow-main\assets\template_matching\template1.png" "D:\xxx mods\helpful tools\NexusDownloadFlow-main\assets\template_matching\template2.png"  It was successful, no errors there.  Then, I ran the command for Custom mode. Then this error showed up.
![powershell_pAyrT8DFfn](https://github.com/user-attachments/assets/f54db854-b66d-4e2a-8b29-7e67f1b7e587)

**Comment by greg-ynx** [comment]
Hi! I'm sorry that NDF didn't worked for you.

After using the add-templates command. Did your templates where copied to the custom_templates folder (in the same location of the NexusDownloadFlow.exe)?

The custom_templates folder needs to be at the same level of the executable for the custom mode to work.

After seeing your issue, I had an idea about just giving the path of your templates to the software so that it just have to search for your images where they are and not duplicates them in another directory.

I'll add this feature in the next hotfix version.

Waiting for your answer,

Greg.

**Comment by DamnPlotArmor** [comment]
yeah, I can see a custom_templates folder in the same location which I was pretty sure was not there before I added the custom templates. Inside the custom_templates folder, it has template1.png and template2.png
![5e6SEkktX7](https://github.com/user-attachments/assets/3aeac048-2e21-444b-9f4e-055d97cfabdf)
![GqDH8tFA3O](https://github.com/user-attachments/assets/d4bbd2e9-de5a-4c98-a143-9639189a64a3)

**Comment by greg-ynx** [comment]
Hm it seems that the path given internally to search for your templates is composed only of there names...

Try to put your templates at the same location of the executable and try to run NDF in custom mode.

Tell me if it works 😅

**Comment by greg-ynx** [comment]
By the way, you don't need to have the whole project in order to use NDF, the NexusDownloadFlow.exe is the only file you need if your intent is only to use it 😉

**Comment by DamnPlotArmor** [comment]
it worked! you were right. I put both of  the template images in the same location of the executable and then ran the command for custom, no errors came this time
![powershell_DDDcRWluAt](https://github.com/user-attachments/assets/b0333d71-8746-480a-8ffd-b82b5e13a332)
So, now do I just open wabbajack and start installing the modlist while the terminal window is open?

**Comment by greg-ynx** [comment]
Great! Yes now that NDF is running you just have to launch the installation of your mod pack on Wabbajack. NDF will click on each Nexus mods page that is opened for you.

Hope that you won't have anymore issues 😁

**Comment by DamnPlotArmor** [comment]
Yes! Thank you so much. It's working.

**Comment by greg-ynx** [comment]
No problem! I'm closing this issue
